# --------------------------------------------------------------------
# Makefile - May 12, 2003
#
# Copyright (c) 2003 ChipData, Inc. All Rights Reserved.
#
# $Id: Makefile,v 1.1 2004/02/17 20:07:06 meding Exp $
#
# --------------------------------------------------------------------

CC=gcc

PLATFORM=linux
API=libcompare.so
BIN=../bin

HEADER=-I../include -I../include/${PLATFORM} -I${JAVA_HOME}/include -I${JAVA_HOME}/include/${PLATFORM}

SRCS=alloc.cpp compare.cpp device.cpp equate.cpp event.cpp exception.cpp hash.cpp jni.cpp match.cpp neighbors.cpp net.cpp print.cpp queue.cpp
OBJS=${SRCS:.cpp=.o}

#CPPFLAGS= -DUNIX_ENV -Dunix=1 -DUNIX_PLATFORM=1 -mimpure-text -shared ${HEADER}
CPPFLAGS= -DUNIX_ENV -Dunix=1 -DUNIX_PLATFORM=1 -shared ${HEADER}



${API}: ${OBJS}
	@[ -d ${BIN} ] || mkdir ../bin
	${CC} ${CPPFLAGS} ${OBJS} -o ${BIN}/${API}

clean:
	rm -f *.o *~ *BAK *stackdump *del *.res ${API}
